# Generated by Django 5.0.7 on 2024-11-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lecturer', 'Giảng viên'), ('student', 'Sinh viên')], default='student', max_length=10),
        ),
    ]
