# Generated by Django 5.0.7 on 2024-09-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_service', '0002_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
