# Generated by Django 5.0.7 on 2024-09-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_service', '0005_rename_user_userquizcompletion_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquizcompletion',
            old_name='quiz',
            new_name='quiz_id',
        ),
    ]
