# Generated by Django 5.0.7 on 2024-12-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
