# Generated by Django 5.0.7 on 2024-09-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('courses_id', models.IntegerField()),
                ('day', models.DateTimeField(blank=True, null=True)),
                ('todo', models.TextField()),
                ('issue', models.TextField()),
                ('plan', models.TextField()),
            ],
        ),
    ]
